dist:     xenial
sudo:     false
language: go
go:
  - 1.11.x
git:
  depth: 1
  go_import_path: github.com/metalkube/terraform-provider-ironic
install:        true
before_script:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
  - sudo unzip /tmp/terraform.zip -d /usr/local/bin
script:
  - make fmt
  - make lint
  - make test
